//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFunctionCalculate")]
public interface IFunctionCalculate
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionCalculate/Number8", ReplyAction="http://tempuri.org/IFunctionCalculate/Number8Response")]
    double Number8(double x, double y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionCalculate/Number8", ReplyAction="http://tempuri.org/IFunctionCalculate/Number8Response")]
    System.Threading.Tasks.Task<double> Number8Async(double x, double y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionCalculate/Number20", ReplyAction="http://tempuri.org/IFunctionCalculate/Number20Response")]
    double Number20(double x, double y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionCalculate/Number20", ReplyAction="http://tempuri.org/IFunctionCalculate/Number20Response")]
    System.Threading.Tasks.Task<double> Number20Async(double x, double y);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IFunctionCalculateChannel : IFunctionCalculate, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FunctionCalculateClient : System.ServiceModel.ClientBase<IFunctionCalculate>, IFunctionCalculate
{
    
    public FunctionCalculateClient()
    {
    }
    
    public FunctionCalculateClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FunctionCalculateClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FunctionCalculateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FunctionCalculateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double Number8(double x, double y)
    {
        return base.Channel.Number8(x, y);
    }
    
    public System.Threading.Tasks.Task<double> Number8Async(double x, double y)
    {
        return base.Channel.Number8Async(x, y);
    }
    
    public double Number20(double x, double y)
    {
        return base.Channel.Number20(x, y);
    }
    
    public System.Threading.Tasks.Task<double> Number20Async(double x, double y)
    {
        return base.Channel.Number20Async(x, y);
    }
}
